### ISSUE TITLE
`getAttachmentFile()` fails with TB 78 but not with TB 90

### ISSUE THREAD

**Issue by sttzr** [sttzr/web-ext-attachments-experiment#1]
When trying to backport the code from https://phabricator.services.mozilla.com/D107403 to Thunderbird 78 as a web ext experiment, there seems to be some code related to `channels`, `scriptSecurityManager` or `streamLoader` that is not compatible with TB78.
This is the error I get inside `getAttachmentFile`:

> [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIChannel.asyncOpen]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: file:///[...]/web-experiment/attachments_tb78/implementation.js :: getAPI/getAttachmentFile/byteArray< :: line 113"  data: no]

Trying this addon in TB90 does actually work!

This is the part that fails with TB78 inside `getAttachmentFile()` at line 113,  when the attachment objects url is actually streamed into a file:
https://github.com/sttzr/web-ext-attachments-experiment/blob/13e022324375810afcda3a6efef35a67162983c8/attachments_tb78/implementation.js#L61-L118
(attachment object is logged correctly in line 93)
What needs to be done to make this work in Thunderbird 78?

**Comment by sttzr** [comment]
Hey @darktrojan, with this demo-addon I'm trying to "backport" your Thunderbird web-ext api `messages.getAttachmentFile()` implementation to Thunderbird 78 as an web-ext-experiment. So I'm trying to convert the code from your patch https://phabricator.services.mozilla.com/D107403 to an web-ext-experiment. However I'm a bit stuck here (see above). Maybe you could have a quick look? Thanks a lot!

**Comment by darktrojan** [comment]
Sorry, but I haven't got an answer to that. FWIW, I get the same failure.

**Comment by sttzr** [comment]
@darktrojan Thanks for looking into it! I spend some more time on it and found out that `nsILoadInfo.SEC_ALLOW_CROSS_ORIGIN_DATA_IS_NULL` has been renamed to `nsILoadInfo.SEC_ALLOW_CROSS_ORIGIN_SEC_CONTEXT_IS_NULL` in TB 80 Beta. This solved the error.
